tweak node detection

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-if ! hash node 2>/dev/null; then
+if ! [ -x /app/.heroku/node/bin/node ]; then
   >&2 echo 'Denali: it looks like Node is not available. Did you add the Denali buildpack *after* the Node buildpack?'
   exit 1
 fi
@@ -12,3 +12,5 @@ fi
 
 echo "Denali"
 exit 0
+
+# LEFT OFF detect failing, not sure why - seems to think node isn't there
